### ISSUE TITLE
How to use your custom kernel?

### ISSUE THREAD

**Issue by haosmos** [Nevuly/WSL2-Linux-Kernel-Rolling#10]
Hello! 😀 I found your project and became interested in it. Looks very promising and interesting!

I just started learning wsl and there is still a lot I don't understand. Could you tell me in a little more detail how I can use your custom kernel? I read the wsl documentation - it says that the `bzImage` file should be placed in the windows user's root folder and in the `.wslconfig` file it should be specified like this:

```
[wsl2]
kernel=C:\\Users\\<USERNAME>\\bzImage
```

I understood it. But I didn't quite understand what needs to be done with bzImage-x86_64-optional_install.tar and bzImage-x86_64-modules_install.tar. 

Could you explain how to use them? They need to be unpacked in the wsl environment and two scripts executed - `modules-install.sh` and `optionals-install.sh`?  Does it matter in what order these scripts should be run?

**Comment by Nevuly** [comment]
@haosmos
Hello!

Thank you for your interest about my custom kernel project :)

To use this kernel, you need to do install process in below:

1. Download bzImage and copy it in ```C:\Users\USERNAME\" directory. And create ```.wslconfig``` in ```C:\Users\USERNAME\```, and write configs like below:
(Before install custom kernel, you must shutdown your WSL2 system)

```
[wsl2]
kernel=C:\\Users\\USERNAME\\vmlinux
```

After write it, turn on your WSL2 and run this command: ```uname -a```
If you get a 6.x.x-WSL2-STABLE+ in ```uname -a```, It installed success.

2. If you need kernel modules, you can install kernel modules in your own WSL2 system.
Download ```bzImage-PLATFORM-modules_install.tar``` and copy it in your WSL2 linux directory (```/home/USERNAME/```)
And unpack it, then execute ```modules-install.sh``` script.
After install modules, please reboot your WSL2 linux.

3. If you need kernel headers or kernel documents, you can install kernel optionals in your own WSL2 system.
Download ```bzImage-PLATFORM-optionals_install.tar``` and copy it in your WSL2 linux directory (```/home/USERNAME/```)
And unpack it, then execute ```optionals-install.sh``` script.
After install optionals, please reboot your WSL2 linux.

If you have more questions, Please re-open this issue!

Thanks!
