### ISSUE TITLE
[QUESTION]What are kernel modules, kernel headers and kernel documents for?

### ISSUE THREAD

**Issue by haosmos** [Nevuly/WSL2-Linux-Kernel-Rolling#11]
Thank you very much for your detailed answer!

Could you please clarify why you may need to install kernel modules, kernel headers and kernel documents? Does this open up some possibilities that are not available in the default wsl?

And do I understand correctly that if I install kernel modules and kernel headers or kernel documents and that if something goes wrong or breaks, then there will be no way to roll back everything? That is, before this you will need to make a backup, right?

**Comment by Nevuly** [comment]
@haosmos 

kernel modules, kernel headers and kernel documents install step is optional.

 * Kernel Modules *

If you need to use kernel features (ex. F2FS, USB and more), install modules.

 * Kernel Headers and Kernel Documents *

If you try to development about kernel modules and DKMS, install optionals.

 * Why It need to install? *

WSL2 system is different how to run Linux kernel.
bzImage not included modules, headers and documents, and also Windows can't install it in Linux system.

So, It need to install by manual.

> And do I understand correctly that if I install kernel modules and kernel headers or kernel documents and that if something goes wrong or breaks, then there will be no way to roll back everything? That is, before this you will need to make a backup, right?

Maybe, If WSL2 running correctly, you can access linux directory in ```explorer.exe```. If you have some problem to install optional packages, you can remove it in Windows.

Thanks.

**Comment by Nevuly** [comment]
Locked conversation for avoid reference this issue when I try to push commits.
