### ISSUE TITLE
Suggestion for using the latest dxgkrnl module source code

### ISSUE THREAD

**Issue by MouriNaruto** [Nevuly/WSL2-Linux-Kernel-Rolling#12]
It looks you are using WSL2-Linux-Kernel's dxgkrnl module implementation for old 5.15 kernel.

In recent days, Microsoft created the dxgkrnl module implementation for newer 6.6 kernel. Here is the way to find.

1. Find the latest tag in https://github.com/microsoft/CBL-Mariner-Linux-Kernel/tags, currently is `rolling-lts/mariner-3/6.6.30.1`, open the tag link, it should be https://github.com/microsoft/CBL-Mariner-Linux-Kernel/tree/rolling-lts/mariner-3/6.6.30.1
2. Find MSFT-Merge/log, currently should be https://github.com/microsoft/CBL-Mariner-Linux-Kernel/blob/rolling-lts/mariner-3/6.6.30.1/MSFT-Merge/log. You will know the dxgkrnl 6.6 branch commit, current should be 423e5044c57566f8267bbb20cf7cf57d1aefb040.
3. Browse the commit tree, for example https://github.com/microsoft/CBL-Mariner-Linux-Kernel/tree/423e5044c57566f8267bbb20cf7cf57d1aefb040

I hope this WSL customized kernel project can use the latest public dxgkrnl implementation from Microsoft.

Kenji Mouri

**Comment by Nevuly** [comment]
@MouriNaruto 

Hello!

Thanks for leaving suggestion about `dxgkrnl` module!

I forgot to check the repository, which caused dxgkrnl to work in old code.

I'll update `dxgkrnl` module in next release.

Thanks!
