### ISSUE TITLE
[BUG] ➜  ~ git:(master) ✗ nvidia-smi  494 segmentation fault  nvidia-smi

### ISSUE THREAD

**Issue by Zhoneym** [Nevuly/WSL2-Linux-Kernel-Rolling#13]
➜  ~ git:(master) ✗ nvidia-smi
Sun May 26 12:43:43 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.42.03              Driver Version: 555.85         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
[1]    494 segmentation fault  nvidia-smi
➜  ~ git:(master) ✗

**Comment by Nevuly** [comment]
@Zhoneym Please check link in below:
https://github.com/microsoft/WSL/issues/11277

Thanks.
