### ISSUE TITLE
[BUG] Docker Desktop not work on 6.9.3 in Ubuntu 24.04 

### ISSUE THREAD

**Issue by DvaMishkiLapa** [Nevuly/WSL2-Linux-Kernel-Rolling#14]
Good afternoon, thank you for your initiative!

Docker Desktop does not seem to work with this kernel. After startup, there is an infinite download.

Everything works fine with the standard kernel.

Windows 11 23H2
Docker Desktop 4.30.0
WSL2 fastfetch:
```bash
                            ....               thesame@theSameAsus
              .',:clooo:  .:looooo:.           -------------------
           .;looooooooc  .oooooooooo'          OS: Ubuntu noble 24.04 x86_64
        .;looooool:,''.  :ooooooooooc          Host: Windows Subsystem for Linux - Ubuntu-24.04 (2.2.4)
       ;looool;.         'oooooooooo,          Kernel: Linux 6.9.3-WSL2-STABLE+
      ;clool'             .cooooooc.  ,,       Uptime: 4 mins
         ...                ......  .:oo,      Packages: 1008 (dpkg)
  .;clol:,.                        .loooo'     Shell: zsh 5.9
 :ooooooooo,                        'ooool     Display (XWAYLAND0): 2560x1600 @ 60Hz
'ooooooooooo.                        loooo.    Display (XWAYLAND1): 800x1280 @ 60Hz
'ooooooooool                         coooo.    WM: WSLg (Wayland)
 ,loooooooc.                        .loooo.    Theme: Yaru [GTK3]
   .,;;;'.                          ;ooooc     Icons: Yaru [GTK3]
       ...                         ,ooool.     Terminal: Windows Terminal
    .cooooc.              ..',,'.  .cooo.      Terminal Font: MesloLGS NF (10pt)
      ;ooooo:.           ;oooooooc.  :l.       CPU: AMD Ryzen 7 6800HS (16) @ 3.19 GHz
       .coooooc,..      coooooooooo.           GPU 1: AMD Radeon RX 6700S (7.96 GiB) [Discrete]
         .:ooooooolc:. .ooooooooooo'           GPU 2: AMD Radeon(TM) Graphics (483.47 MiB) [Integrated]
           .':loooooo;  ,oooooooooc            Memory: 874.48 MiB / 5.78 GiB (15%)
               ..';::c'  .;loooo:'             Swap: 524.00 KiB / 4.00 GiB (0%)
                                               Disk (/): 17.72 GiB / 1006.85 GiB (2%) - ext4
                                               Disk (/mnt/c): 510.29 GiB / 634.86 GiB (80%) - 9p
                                               Disk (/mnt/wsl/docker-desktop/docker-desktop-user-distro): 55.32 MiB / 1006.85 GiB (0%) - ext4
                                               Locale: en_US.UTF-8
```
I have installed all the modules you provide.

wslconfig:
```conf
[wsl2]
memory=6GB
swap=4GB
# processors=4
networkingMode=mirrored
kernel=C:\\Users\\thesa\\bzImage-x86_64

[experimental]
sparseVhd=true
autoMemoryReclaim=gradual

```

**Comment by Nevuly** [comment]
@DvaMishkiLapa

Hello, Thanks for leaving issue!

Can you give me a logs when It try to infite download in docker desktop?

Thanks!

**Comment by Nevuly** [comment]
@DvaMishkiLapa 

Check this links in below:

https://docs.docker.com/desktop/release-notes/ (Docker Official Document. See Known issues tab)
https://askubuntu.com/questions/1511725/ubuntu-24-04-docker-desktop-is-not-starting (Ask Ubuntu)

Docker Desktop seems not support Ubuntu 24.04 yet. It need to execute this commands in below:

`sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0`
`systemctl --user restart docker-desktop`

If you resolved problem after execute that commands, please leave comment.

Thanks!

**Comment by Nevuly** [comment]
Docker still not working problem occured in this kernel.
I try to find solution to fix this problem.

Issue will be update in https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/issues/18.

**Comment by Nevuly** [comment]
[FINAL ISSUE PROGRESS]

Issue level: **critical**

https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/fd1e0a3f0fcd5d593eba801068f1b4c27d8a1116
https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/8e13f3d4a8ff78916587082bb722a9c046f1a311

These 2 commits made this issue.

I used `wsl-6.8-rolling` final version of defconfigs, and It already included that 2 commits.

I'll rollback to official WSL2 defconfigs.

**Comment by Nevuly** [comment]
@DvaMishkiLapa 

I fixed defconfigs to fix this issue.

WSL2-Linux-Kernel-Rolling: https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/5bccb180ea70d17ff3e5f656d127fa72b41a2018
WSL2-Linux-Kernel-Rolling-LTS: https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling-LTS/commit/126f86eeea73f57a336772b2e0c0afa08e3f9e57

This patch applied in lastest builds (`6.9.7`, `6.6.36`)

Thanks!
