### ISSUE TITLE
[BUG] Logic in modules-install.sh is broken

### ISSUE THREAD

**Issue by juergenpf** [Nevuly/WSL2-Linux-Kernel-Rolling#15]
IMHO the logic of the file checking in modules-install.sh is broken.

Lets assume, the first file you check doesn't exist. Then you set file_checker=0. If now the next file exists, you overwrite that immediately with file_checker=1. When you then at the end check the value, you'll never notice, that the first file was missing. You need to rework this.

**Comment by Nevuly** [comment]
@juergenpf 

Hello, Thanks for leaving issue!

I'll apply more better file check solution in installer script.

Thanks!

**Comment by Nevuly** [comment]
@juergenpf 

I fixed modules-install.sh script file check process.

You can check script in below:

https://gist.github.com/Nevuly/cf1d17db72cdfde6ed149461eef0215c

Thanks!
