### ISSUE TITLE
[QUESTION] About the sources

### ISSUE THREAD

**Issue by Prince213** [Nevuly/WSL2-Linux-Kernel-Rolling#17]
Hi, I found this project while searching for a newer WSL2 kernel. It looks promising but I want to know what's the difference with the official upstream kernel? For example, what patches did you apply and where did those came from? How was the config generated? Thanks.

**Comment by Nevuly** [comment]
@Prince213 

Hi.

This project aims to support latest kernel for WSL2. (Rolling Release)

Almost codes came from official microsoft WSL2 kernel and Mariner kernel source codes.

Kernel defconfigs also came from official WSL2 kernel, and modified configs for avoid security issues and support some kernel features.

Thanks.

**Comment by Nevuly** [comment]
I close and lock conversation for avoid reference this issue when I try to push commits.

If you have more questions, please create new issue.

Thanks!
