### ISSUE TITLE
[BUG] Docker Desktop doesn't start up with this kernel for WSL2

### ISSUE THREAD

**Issue by justinkb** [Nevuly/WSL2-Linux-Kernel-Rolling#18]
#14 shouldn't have been closed. This issue has nothing to do with ubuntu, *Docker Desktop for Windows* uses WSL2 internally via two "distros" it installs.

Your suggestion also doesn't solve anything, kernel.apparmor_restrict_unprivileged_userns isn't even part of this kernel, it's introduced by an ubuntu kernel specific patch.

The specific error reported by Docker Destop is "running engine: waiting for the Docker API: context deadline exceeded"

**Comment by Nevuly** [comment]
@justinkb 

1. Ensure that the same issue occurs in the WSL2 official kernel environment.
2. I don't use Docker Desktop in a WSL2 environment, so I don't know the issue clearly.

If you want to resolve the issue, and if this issue occurs in the kernel, please get the relevant logs.

**Comment by justinkb** [comment]
The issue is not present if I comment #kernel=.. in . wslconfig . I will
try to find error logs in the wsl2 docker-desktop distro userspace

**Comment by Nevuly** [comment]
@justinkb 

I checked it in my environment, and I confirmed it wasn't working.

I'm checking for a solution.

Thank you.

**Comment by Nevuly** [comment]
```
-------------------------------------------------------------------------------->8
[2024-06-30T10:10:57.259732295Z][com.docker.backend][W] system telemetry disabled, custom otlp endpoint "https://desktop.observability-stage.docker.com" will be ignored
[2024-06-30T10:10:57.260048707Z][com.docker.backend.sys] maximum number of file descriptors is 1048576
[2024-06-30T10:10:57.260152739Z][com.docker.backend.report] backend crashed, dumping error to file and reporting to user: setting up backend: checking compatibility: required compatibility check: Virtualization support
[2024-06-30T10:10:57.260333728Z][com.docker.backend.report] reporting error to user: setting up backend: checking compatibility: required compatibility check: Virtualization support
[2024-06-30T10:10:57.260568093Z][com.docker.backend.report] error server listening on <HOME>/.docker/desktop/error.reporter.sock
[2024-06-30T10:10:57.260685681Z][com.docker.backend.ipc] run 2ea10843-ErrorReportAPI for component report on <HOME>/.docker/desktop/error.reporter.sock
-------------------------------------------------------------------------------->8
```

It seems backend crashed, and It can't communicate to host.
I'll check defconfig features.

**Comment by justinkb** [comment]
let me know if I can help figure out the issue

**Comment by Nevuly** [comment]
locked this conversation for avoid reference this issue when I try to push commits.

**Comment by Nevuly** [comment]
@justinkb 

This issue is added in known issue list in below:
https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/issues/19

I can't find solution to fix this problem.

But, It have temporarily solution in below:
https://github.com/Locietta/xanmod-kernel-WSL2/issues/64

If I find to fix this issue, I'll update it.

Thanks.

**Comment by Nevuly** [comment]
Update in 24.07.01

I try to use 6.8.0 build, It works correctly.

I think some kernel features are missing and not defined in defconfig.

I try to check it. Maybe It will fix in next build or above.

**Comment by Nevuly** [comment]
[FINAL ISSUE PROGRESS]

Issue level: **critical**

https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/fd1e0a3f0fcd5d593eba801068f1b4c27d8a1116
https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/8e13f3d4a8ff78916587082bb722a9c046f1a311

These 2 commits made this issue.

I used `wsl-6.8-rolling` final version of defconfigs, and It already included that 2 commits.

I'll rollback to official WSL2 defconfigs.

**Comment by justinkb** [comment]
that's great. I'll try to do a git bisect to figure out the exact cause, if we have a known working commit

**Comment by Nevuly** [comment]
> that's great. I'll try to do a git bisect to figure out the exact cause, if we have a known working commit

Thank you for your help.

**Comment by Nevuly** [comment]
Now, I triggered build 6.9.7 kernel again.

https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/actions/runs/9744124023

@justinkb 
Can you test it when It build finished?

**Comment by Nevuly** [comment]
> just checked here, [082bd5a](https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/082bd5a646e6a33c4fe4f8af5fc2eb41fc726f4f) is definitely the first bad commit, so one of the changes in the config there is the culprit. shouldn't be that hard to pin down to an exact kernel config option

I'll check it ASAP!

Thank you so much to help this problem :)

**Comment by Nevuly** [comment]
![image](https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/assets/32860694/44d73395-61ec-40a8-9880-e7e965aae107)

@justinkb 

Now, It works again. And It released.

Thank you so much to resolve this problem!
