### ISSUE TITLE
[BUG] version linux-wsl-stable-6.9.7

### ISSUE THREAD

**Issue by dmitrykok** [Nevuly/WSL2-Linux-Kernel-Rolling#21]
linux-wsl-stable-6.9.7
no kernel folder in bzImage-x86_64-modules_install.tar.gz
./modules-install.sh get error 

 !!-- [1/14] kernel directory Not Exist! --!!
 !!-- Abort install kernel modules package --!!

sudo ./modules-install.sh

 WSL2 Kernel modules package installer
 Made by Nevuly

 Start to install kernel modules package.

 Checking kernel version...

 Kernel version found.
 Kernel version: 6.9.7

 Checking kernel modules package folder and files...

 Stable kernel detected.

 Checking kernel module files... [13 Modules]

 !!-- [1/14] kernel directory Not Exist! --!!
 !!-- Abort install kernel modules package --!!

**Comment by dmitrykok** [comment]
linux-wsl-stable-6.9.7
./optionals-install.sh get error 

 !!-- Kernel modules package folder not found! --!!
 !!-- Abort install kernel optionals package --!!

**Comment by Nevuly** [comment]
@dmitrykok 

Hi,

Thanks for leaving issue.

I checked 6.9.7 kernel module and optional tarball files, It is empty.

Maybe compress process have some problem.

I'll check it.

Thanks.

**Comment by Nevuly** [comment]
5bccb180ea70d17ff3e5f656d127fa72b41a2018

After applied this commit, Some kernel module drivers were disabled. (NVMe, Net, USB Serial, Netfilter, IPv4)
And that reason kernel directory not created in `module_install` process.

I'll delete check kernel directory in module install script.

Thanks.

**Comment by Nevuly** [comment]
I updated module install script.

WSL2-Linux-Kernel-Rolling: https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/f45185f6741912110447f809fa9e53ae5b97581b
WSL2-Linux-Kernel-Rolling-LTS: https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling-LTS/commit/e4af3819b28852931095076459884c87b2255f2c

You can check install script in below:
https://gist.github.com/Nevuly/cf1d17db72cdfde6ed149461eef0215c

If you have more questions or issues, please create new issue.

Thanks!
