### ISSUE TITLE
The structure of bzImage-x86_64-modules_install.tar.gz is really not easy to use

### ISSUE THREAD

**Issue by pffang** [Nevuly/WSL2-Linux-Kernel-Rolling#4]
Can you remove the first level folder "bzImage-x86_64-modules_install"?
Then we can extract the /lib/modules/6.6.1-WSL2-STABLE+ to filesystem directly.

**Comment by Nevuly** [comment]
Thanks for leaving issue. It will apply in next release. I need to test it in my local PC.

**Comment by Nevuly** [comment]
@pffang 

I applied your request in my gh-action script. It will apply in next release.

Thanks.

**Comment by pffang** [comment]
"bzImage-x86_64-modules_install" is back...

**Comment by Nevuly** [comment]
> "bzImage-x86_64-modules_install" is back...

@pffang 

Check about Nevuly/WSL2-Linux-Kernel-Rolling#6.

I added install script for loading kernel modules correctly.

> Then we can extract the /lib/modules/6.6.1-WSL2-STABLE+ to filesystem directly.

bzImage-x86_64-modules_install file was created to install modules without a separate kernel build on the WSL2 system.

If you build directly from a WSL2, you don't need to use that file.
