### ISSUE TITLE
[HELP] compiled kernel doesn't have "usb-storage" module

### ISSUE THREAD

**Issue by VPraharsha03** [Nevuly/WSL2-Linux-Kernel-Rolling#6]
I've forked and tried compiling a kernel with USB Storage support by enabling `CONFIG_USB_STORAGE=y` (https://github.com/VPraharsha03/WSL2-Linux-Kernel-Rolling/blob/47a339a3f960dc2e9a5ca5d57aed122b4d2d78f5/arch/x86/configs/config-wsl-x86#L2896)

but when I run `sudo modprobe usb-storage` I get an error stating it doesn't exist

the kernel can be found here: https://github.com/VPraharsha03/WSL2-Linux-Kernel-Rolling/actions/runs/7042383876

**Comment by Nevuly** [comment]
@VPraharsha03 I think you need to build module libraries.

Check this 2 commit in below.

https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/babf8531bca497fcda3646a3c3a24368fcec8214
https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/21dd2c06aa1ea8504e524937237aac4f296a8dfb

**Comment by Nevuly** [comment]
@VPraharsha03 Okay.

I will check it on my WSL2 system and reply to you.

Thanks for your report.

**Comment by VPraharsha03** [comment]
one more thing i've included a [custom version string](https://github.com/VPraharsha03/WSL2-Linux-Kernel-Rolling/blob/b5a9fada3630f121ebdfb2e04d0307b70beb1c1a/arch/x86/configs/config-wsl-x86#L32) but it isn't being reflected in `uname -r`

**Comment by Nevuly** [comment]
@VPraharsha03 I checked it in my local WSL2.

I try to use this command  `sudo modprobe usb-storage`, It nothing happend.

![image](https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/assets/32860694/d71b3a1e-6b6b-4d97-aff9-d9cd04c5c65b)

Maybe, you need to build modules package, and It must be located under /lib/modules/.

If you need to test kernel, I'll send to you.

**Comment by VPraharsha03** [comment]
> @VPraharsha03 I checked it in my local WSL2.
> 
> I try to use this command  `sudo modprobe usb-storage`, It nothing happend.
> 
> ![image](https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/assets/32860694/d71b3a1e-6b6b-4d97-aff9-d9cd04c5c65b)
> 
> Maybe, you need to build modules package, and It must be located under /lib/modules/.
> 
> If you need to test kernel, I'll send to you.
> 

@Nevuly 

I think i've included back all the required commands in build.yml ? do i've to add anything more to build modules package ?

Please share with me the kernel, thanks a lot

**Comment by Nevuly** [comment]
@VPraharsha03 

Here's bzImage and modules.

[bzImage-modules_install.tar.gz](https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/files/13533839/bzImage-modules_install.tar.gz)

[bzImage-Test.zip](https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/files/13533838/bzImage-Test.zip)

Check location and permissions in below.

![image](https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/assets/32860694/06963ff6-9564-4462-b171-342580be2941)


> I think i've included back all the required commands in build.yml ? do i've to add anything more to build modules package ?
> 

I checked your repo, It is correct. But It will not install automatically on your WSL2. So you need to install it manually.

That reason why am I need to make shell script to install it more easily.

**Comment by VPraharsha03** [comment]
@Nevuly yeah i do know that, i followed by copying compiled modules to `/lib/modules`  

i'll test with your compiled kernel & modules later

**Comment by Nevuly** [comment]
@VPraharsha03

I made test install script for module install steps.

After build with gh-actions, download your own modules_install compressed file.

And copy to linux with this script, and try to run it with `sudo`.

If you have any issues, please tell me.

NOTICE
**This script must be locate in modules_install root folder. like below:**

![image](https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/assets/32860694/534b2c3f-d7ee-4f7c-8275-9714f70ff0f6)

[install.zip](https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/files/13560085/install.zip)

**Comment by Nevuly** [comment]
Make kernel module again. I'll add install script.

Thanks for your report.
