### ISSUE TITLE
`Module f2fs not found` after installing kernel module packages

### ISSUE THREAD

**Issue by ColorfulRhino** [Nevuly/WSL2-Linux-Kernel-Rolling#7]
Hello!

First of, thanks for auto-releasing this kernel!

However, I am having an issue, or problems understanding. I need some additional modules which are not enabled in the default kernel, like modules for the `f2fs` filesystem for example.
My understanding is, that you packaged alll available modules in the `bzImage-x86_64-modules_install` and `bzImage-x86_64-optional_install`. So I extracted both and did a `sudo optionals-install.sh` in both folders.
After a reboot (`wsl --shutdown`, wait 10 seconds), doing `modprobe f2fs` still gives the error `modprobe: FATAL: Module f2fs not found in directory /lib/modules/6.8.1-WSL2-STABLE+`

Am I misunderstanding how your additional kernel module packages work?

Thank you!

**Comment by Nevuly** [comment]
@ColorfulRhino 

Hi, Thanks for leaving issue!

I checked in defconfigs, It not set to compile `f2fs` module.

https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/blob/c1a95f4c2d9f2add00155ed48a5bb75fcaf8d798/arch/x86/configs/config-wsl-x86#L3491
https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/blob/c1a95f4c2d9f2add00155ed48a5bb75fcaf8d798/arch/arm64/configs/config-wsl-arm64#L3633

That defconfigs imported from official MSFT WSL2 kernel, and I just updated to use in latest kernel.
(If Microsoft developers have not configured some kernel modules to be compiled, this kernel will not be compiled the same way.)

If you need it, just enable it in `menuconfig` or make PR to enable it.

I look forward to your reply.

Thanks!
