### ISSUE TITLE
Disable RSEQ for ARM64 build

### ISSUE THREAD

**Issue by PeronGH** [Nevuly/WSL2-Linux-Kernel-Rolling#9]
As pointed out in https://github.com/microsoft/WSL/issues/11274, `CONFIG_RSEQ=y` on ARM64 WSL can increase the frequency of RCU stalls. Maybe RSEQ should be temporally disabled until the issue is resolved.

**Comment by Nevuly** [comment]
@PeronGH 

Thanks for leaving issue!

I'll apply it in arm64 defconfig.

It'll apply in next release.

Thank you!

**Comment by Nevuly** [comment]
@PeronGH 

I applied your defconfig request in below:
WSL2-Linux-Kernel-Rolling: https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/commit/bd24c1518d8701a5f1995e17e6fad8f24eb0cf96
WSL2-Linux-Kernel-Rolling-LTS: https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling-LTS/commit/3aaa176a2577034db737b84511aafdfaa11303f7

If you have problems or questions, please reopen this issue.

Thank you!
